language: python

services:
- docker

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "nightly"  # nightly build

matrix:
  include:
    - os: windows
      language: sh
      python: "3.x"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - ls /c/Python
      env: PATH=/c/Python:/c/Python/Scripts:$PATH

install:
  - pip3 install -r requirements.txt

script:
  - python3 ./qmk -h
