language: python

services:
- docker

os:
  - linux
  - osx

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "nightly"  # nightly build

matrix:
  include:
    - os: windows
      language: sh
      python: "3.x"
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -r requirements.txt

script:
  - python3 ./qmk -h
